# Generated by Django 4.2.9 on 2024-03-26 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('achievemets', '0002_achievement_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_image',
            field=models.FileField(blank=True, null=True, upload_to='achievement_images/'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
