# Generated by Django 4.2.9 on 2024-04-01 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('achievemets', '0004_alter_achievement_achievement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/achievement_images/'),
            preserve_default=False,
        ),
    ]
