# Generated by Django 4.2.9 on 2024-04-21 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_alter_entity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ctatext', models.CharField(max_length=255)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='media/solutions_images/')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
    ]
