# Generated by Django 4.2.9 on 2024-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/license_images/'),
        ),
    ]
