# Generated by Django 4.2.9 on 2024-04-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_alter_license_solution_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='solution_image',
            new_name='license_images',
        ),
    ]
