# Generated by Django 4.2.9 on 2024-04-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_rename_solution_image_license_license_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='license',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
