# Generated by Django 4.2.9 on 2024-08-05 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Homeview", "0003_alter_homeview_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="homeview",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="homeview",
            name="image",
            field=models.ImageField(upload_to="homeview_images/"),
        ),
        migrations.AlterField(
            model_name="homeview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
