# Generated by Django 4.2.9 on 2024-07-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_created_by_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(default=list, null=True),
        ),
    ]
