# Generated by Django 4.2.9 on 2024-08-10 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
