# Generated by Django 4.2.9 on 2024-08-13 20:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True, related_name="related_to", to="product.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="units_left",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_locations",
                        to="product.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DropOffPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("charges", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_off_points",
                        to="product.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="drop_off_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.dropoffpoint",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.location",
            ),
        ),
    ]
