# Generated by Django 4.2.9 on 2024-07-12 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0003_alter_entity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/logo')),
                ('entity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
    ]
