# Generated by Django 4.2.9 on 2024-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_solution_created_at_solution_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_image',
            field=models.FileField(blank=True, null=True, upload_to='solutions_images/'),
        ),
    ]
