# Generated by Django 4.2.9 on 2024-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_solution_ctatext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_image',
            field=models.FileField(blank=True, null=True, upload_to='media/solutions_images/'),
        ),
    ]
