# Generated by Django 4.2.9 on 2024-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_alter_solution_solution_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
