# Generated by Django 4.2.9 on 2024-07-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('asset_id', models.CharField(max_length=100)),
                ('public_id', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=50)),
            ],
        ),
    ]
