# Generated by Django 4.2.9 on 2024-01-30 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("receiver", models.CharField(max_length=255)),
                ("message_content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_incoming", models.BooleanField(default=False)),
            ],
        ),
    ]
