# Generated by Django 4.2.9 on 2024-03-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ctatext', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('entity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
    ]
