# Generated by Django 4.2.9 on 2024-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroPage', '0002_heropage_created_at_heropage_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropage',
            name='image',
            field=models.ImageField(upload_to='webbackend/HeroPage/hero_images'),
        ),
    ]
