# Generated by Django 4.2.9 on 2024-03-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroPage', '0003_alter_heropage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropage',
            name='image',
            field=models.ImageField(upload_to='media/hero_images'),
        ),
    ]
