# Generated by Django 4.2.9 on 2024-04-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('testimonial_image', models.ImageField(upload_to='media/testimonial_images/')),
                ('entity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
        ),
    ]
